### ISSUE TITLE
Only empty files are written

### ISSUE THREAD

**Issue by tux93** [un-pogaz/Now-Playing-in-Texts#10]
For me the plugin writes only empty files, the VLC Messages console shows the following errors:
```
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
lua debug: [Now Playing texts] update_files()
lua warning: Error while running script ~/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function meta_changed(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:532: bad argument #2 to 'format' (number has no integer representation)
```
VLC version: 3.0.21
Lua 5.3.6

**Comment by un-pogaz** [comment]
Hum, can send me the file that cause the bug?

This log doesn't provide me enough information to solve it.

**Comment by tux93** [comment]
So far it happens with any file I tried playing, I uploaded an example here:
https://owncloud.tux93.de/s/RqW3Bb7Y96iHCga

**Comment by un-pogaz** [comment]
Work perfectly for me.

So, if is not a Metadata/file error, is probably another Windows/Linux unparity shenanigans, Sweet /s
Because Yes! This is a things, there is a precedent #2.

Can you send a log with this [test version](https://raw.githubusercontent.com/un-pogaz/Now-Playing-in-Texts/dev-test/Now%20Playing%20in%20Texts.lua).

**Comment by tux93** [comment]
Here you go:
[vlc_debug.log](https://github.com/user-attachments/files/16487474/vlc_debug.log)

**Comment by un-pogaz** [comment]
Okay, can you retry with this one [test version](https://raw.githubusercontent.com/un-pogaz/Now-Playing-in-Texts/dev-test/Now%20Playing%20in%20Texts.lua)?

(this could take a while as I'm still blindly trying to figure out exactly what's wrong)

**Comment by un-pogaz** [comment]
Okay, certainly [the last one](https://raw.githubusercontent.com/un-pogaz/Now-Playing-in-Texts/dev-test/Now%20Playing%20in%20Texts.lua).

**Comment by tux93** [comment]
Yes, that appears to be working: the `np_*.txt` files have content now!
[debug-lua_14:51.log](https://github.com/user-attachments/files/16487602/debug-lua_14.51.log)

**Comment by un-pogaz** [comment]
Yes.
I push a release with the fix.

For the reccord: at some point, a need to truncate value and a used a some... *homebrew* solution (the bug was here). In reviewing the lua doc, I realized that there was a build-in fuction that does exactly what I'm looking for and this one work suprisley mush better (jesus, I'm so dump).

Thanks more the report and your time.
Have a nice day.
