### ISSUE TITLE
filename1 not appearing in .txt files?

### ISSUE THREAD

**Issue by Thexterax** [un-pogaz/Now-Playing-in-Texts#5]
Hey there, trying to get the filename without extensions but I can't see "filename1". It's not showing up in
%appdata%\Roaming\vlc 

Am I doing something wrong?

**Comment by un-pogaz** [comment]
1) Be sure to use the last version.
2) Please, could you share with me the code/txt of your custome file.
3) There are a debug file named "np_metadata.txt" that contain all usable metadata/tag name for the curent track played. If `filename1` doesn't appear in this file, then you couldn't use it (although it seems very unlikely)

**Comment by Thexterax** [comment]
I am using the latest version.

What do you mean with custome file & expected file name?

np_metadata.txt has "{filename1}:" yes.

Am I supposed to change the .lua file to get the filename1 to show up? If yes, please advice on how to do so.

**Comment by un-pogaz** [comment]
No, you don't need to edit the lua.

Now Playing in Texts integrates a system of custom files.

For you, you just need to create a file "np_custom.txt" with this text inside
```{filename1}```
and a file "np_custom_out.txt" will be created with the file name, without extension.

To learn more about the custom file system, I recommend you to read the doc "Now Playing in Texts - doc.xhtml" [download](https://github.com/un-pogaz/Now-Playing-in-Texts/releases/download/2.4/Now.Playing.in.Texts.-.doc.xhtml) (open the file i your web brower)

(And nope, Now Playing in Texts does not create a np_filename1.txt. If he had to create a file for each metadata, it would be very quickly the mess in your folder with full of file everywhere, hence the creation of the system for custom files)
