### ISSUE TITLE
better install instructions needed

### ISSUE THREAD

**Issue by sainsdy** [un-pogaz/Now-Playing-in-Texts#6]
The doc file needs to be a bit more thorough. I had to look in previous support issues to find that ticking the plugin in View was to enable it. There was nothing in the instructions about this. Having not added any plugins to VLC before I was thrown off. Once ticked it worked a charm. May be just rewrite the installation instructions and Functioning bits to be a bit clearer?

Cheers

**Comment by un-pogaz** [comment]
I hadn't done it, because it's how all VLC plugins work, but it's true that it's not intuitive. Thanks for pointing this out.

Done
